version: "3"
services:
  food-app-postgres:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=food_app_dev
      - POSTGRES_USER=food_app_dev
      - POSTGRES_PASSWORD=food_app_dev
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data/db

volumes:
  postgres-data: