// <auto-generated />
using System;
using Food_Delivery_App.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Food_Delivery_App.Migrations
{
    [DbContext(typeof(FoodAppContext))]
    [Migration("20220718113928_InitialCreatePostgresql")]
    partial class InitialCreatePostgresql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Food_Delivery_App.Models.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<Guid?>("restaurantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("restaurantId");

                    b.ToTable("foods");
                });

            modelBuilder.Entity("Food_Delivery_App.Models.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isDeliveryFree")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("restaurants");
                });

            modelBuilder.Entity("Food_Delivery_App.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("credit")
                        .HasColumnType("double precision");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Food_Delivery_App.Models.Food", b =>
                {
                    b.HasOne("Food_Delivery_App.Models.Restaurant", "restaurant")
                        .WithMany("foodCatalogue")
                        .HasForeignKey("restaurantId");

                    b.Navigation("restaurant");
                });

            modelBuilder.Entity("Food_Delivery_App.Models.Restaurant", b =>
                {
                    b.Navigation("foodCatalogue");
                });
#pragma warning restore 612, 618
        }
    }
}
