// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeSheet.Contexts;

#nullable disable

namespace TimeSheet.Migrations
{
    [DbContext(typeof(TimeSheetContext))]
    [Migration("20220607120251_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TimeSheet.Models.Category", b =>
                {
                    b.Property<int>("categoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoryID"), 1L, 1);

                    b.Property<string>("categoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TimeSheet.Models.Client", b =>
                {
                    b.Property<int>("clientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("clientID"), 1L, 1);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("zip")
                        .HasColumnType("int");

                    b.HasKey("clientID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("TimeSheet.Models.Member", b =>
                {
                    b.Property<int>("memberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("memberID"), 1L, 1);

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("hoursPerWeek")
                        .HasColumnType("real");

                    b.Property<string>("memberName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("memberID");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("TimeSheet.Models.Project", b =>
                {
                    b.Property<int>("projectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("projectID"), 1L, 1);

                    b.Property<int?>("currentclientID")
                        .HasColumnType("int");

                    b.Property<int?>("memberID")
                        .HasColumnType("int");

                    b.Property<string>("projectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("projectID");

                    b.HasIndex("currentclientID");

                    b.HasIndex("memberID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("TimeSheet.Models.TimeSheetClass", b =>
                {
                    b.Property<int?>("sheetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("sheetID"), 1L, 1);

                    b.Property<int?>("categoryID")
                        .HasColumnType("int");

                    b.Property<int?>("clientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("memberID")
                        .HasColumnType("int");

                    b.Property<double>("overtime")
                        .HasColumnType("float");

                    b.Property<int?>("projectID")
                        .HasColumnType("int");

                    b.Property<double>("time")
                        .HasColumnType("float");

                    b.HasKey("sheetID");

                    b.HasIndex("categoryID");

                    b.HasIndex("clientID");

                    b.HasIndex("memberID");

                    b.HasIndex("projectID");

                    b.ToTable("TimeSheets");
                });

            modelBuilder.Entity("TimeSheet.Models.Project", b =>
                {
                    b.HasOne("TimeSheet.Models.Client", "currentClient")
                        .WithMany()
                        .HasForeignKey("currentclientID");

                    b.HasOne("TimeSheet.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("memberID");

                    b.Navigation("Member");

                    b.Navigation("currentClient");
                });

            modelBuilder.Entity("TimeSheet.Models.TimeSheetClass", b =>
                {
                    b.HasOne("TimeSheet.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("categoryID");

                    b.HasOne("TimeSheet.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("clientID");

                    b.HasOne("TimeSheet.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("memberID");

                    b.HasOne("TimeSheet.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("projectID");

                    b.Navigation("Category");

                    b.Navigation("Client");

                    b.Navigation("Member");

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
